services:
  delty:
    container_name: delty
    build: .
    command: bash -c "cron && ./wait-for-db.sh db && python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"

    env_file: .env # Here we place all the secrets that should not be exposed in GH
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_app

  delty-worker:
    container_name: delty-worker
    build: .
    command: bash -c "./wait-for-db.sh db && python manage.py rundramatiq"
    env_file: .env # Here we place all the secrets that should not be exposed in GH
    volumes:
      - .:/app
    depends_on:
      - db
      - redis_app

  db:
    container_name: db
    image: postgres:latest
    stop_signal: SIGINT # Fast shutdown.
    environment:
      - POSTGRES_DB=delty
      - POSTGRES_USER=delty_user
      - POSTGRES_PASSWORD=delty_pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h localhost -p 5432 -U delty_user -d delty"
      timeout: 30s
      interval: 5s
    ports: [ 5432:5432 ]
    volumes:
      - db_data:/var/lib/postgresql/data

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"  # Edge port
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-s3-bucket.sh:/etc/localstack/init/ready.d/init-s3-bucket.sh"

  redis_app:
    image: redis
    ports: [ 6379:6379 ]
    volumes: [ redis_app:/var/lib/redis/data ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]

volumes:
  redis_app:
  db_data:
