services:
  delty:
    container_name: delty
    build: .
    command: bash -c "poetry run python manage.py migrate \
      && (poetry run python manage.py runserver 0.0.0.0:8000 & poetry run python manage.py run_grpc_server)"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "50051:50051"
    depends_on:
      - db
      - redis
      - s3

  delty-worker:
    container_name: delty-worker
    build: .
    command: bash -c "poetry run python manage.py rundramatiq"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - s3

  db:
    container_name: db
    image: postgres:15
    stop_signal: SIGINT # Fast shutdown.
    environment:
      - POSTGRES_DB=delty
      - POSTGRES_USER=delty_user
      - POSTGRES_PASSWORD=delty_pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h localhost -p 5432 -U delty_user -d delty"
      timeout: 30s
      interval: 5s
    ports: [ 5432:5432 ]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./system/scripts/airflow.sql:/docker-entrypoint-initdb.d/airflow.sql

  s3:
    container_name: s3
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: sh
    command: -c 'mkdir -p /data/selected-element-html-s3-bucket && minio server --address 0.0.0.0:9000 --console-address ":9001" /data'
    ports:
      - "9000:9000" # MinIO console
      - "9001:9001" # MinIO admin console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    container_name: redis
    stop_signal: SIGINT # Fast shutdown.
    image: redis:7.4
    ports: [ 6379:6379 ]
    volumes: [ redis_data:/var/lib/redis/data ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]

  airflow:
    container_name: airflow
    build:
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://delty_user:delty_pass@db:5432/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GRPC_SERVER_ADDRESS=delty:50051
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
      - delty
      - s3

volumes:
  redis_data:
  db_data:
  minio_data:
