# Generated by Django 5.0.6 on 2024-07-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0002_alter_selectedelement_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagesnapshot",
            name="content",
        ),
        migrations.AlterField(
            model_name="pagesnapshot",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="snapshots",
                to="delty.urladdress",
            ),
        ),
    ]
