# Generated by Django 5.0.6 on 2024-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0003_remove_pagesnapshot_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urladdress",
            name="url",
            field=models.URLField(max_length=2083, unique=True),
        ),
    ]
