# Generated by Django 5.0.6 on 2024-07-28 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration class for altering the database schema.

    This migration performs the following operations:
    - Remove field selected_element from crawlingjob
    - Alter field address on pagesnapshot
    - Create model ElementSnapshot
    - Add field latest_element_snapshot to crawlingjob
    - Delete model SelectedElement

    Dependencies:
        - delty.0004_alter_urladdress_url

    Operations:
        - RemoveField
        - AlterField
        - CreateModel
        - AddField
        - DeleteModel
    """

    dependencies = [
        ("delty", "0004_alter_urladdress_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crawlingjob",
            name="selected_element",
        ),
        migrations.AlterField(
            model_name="pagesnapshot",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="page_snapshots",
                to="delty.urladdress",
            ),
        ),
        migrations.CreateModel(
            name="ElementSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("selector", models.TextField()),
                ("content", models.TextField()),
                ("hash", models.CharField(max_length=64)),
                ("diff", models.TextField(default=None)),
                ("version", models.IntegerField(default=1)),
                (
                    "page_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delty.pagesnapshot",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("page_snapshot", "selector", "hash"),
                    ("page_snapshot", "selector", "version"),
                },
            },
        ),
        migrations.AddField(
            model_name="crawlingjob",
            name="latest_element_snapshot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="delty.elementsnapshot",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SelectedElement",
        ),
    ]
