# Generated by Django 5.0.6 on 2024-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0005_remove_crawlingjob_selected_element_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementsnapshot",
            name="diff",
            field=models.TextField(default=None, null=True),
        ),
    ]
