# Generated by Django 5.0.6 on 2024-08-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0007_elementsnapshot_crawling_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlingjob",
            name="selector",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crawlingjob",
            name="latest_element_snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="delty.elementsnapshot",
            ),
        ),
    ]
