# Generated by Django 5.0.6 on 2024-08-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0008_crawlingjob_selector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementsnapshot",
            name="content_path",
            field=models.TextField(default=""),
        ),
    ]
