# Generated by Django 5.0.6 on 2024-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0009_elementsnapshot_content_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlingjob",
            name="iframe_height",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crawlingjob",
            name="iframe_width",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crawlingjob",
            name="user_agent",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
