# Generated by Django 5.0.6 on 2024-08-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0010_crawlingjob_iframe_height_crawlingjob_iframe_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementsnapshot",
            name="crawling_job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="element_snapshots",
                to="delty.crawlingjob",
            ),
        ),
    ]
