# Generated by Django 5.0.6 on 2024-08-27 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delty", "0011_alter_elementsnapshot_crawling_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elementsnapshot",
            name="content",
        ),
        migrations.RemoveField(
            model_name="elementsnapshot",
            name="diff",
        ),
    ]
