name: Test

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: delty
          POSTGRES_USER: delty_user
          POSTGRES_PASSWORD: delty_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgres://delty_user:delty_pass@localhost:5432/delty"
      DJANGO_SETTINGS_MODULE: "app.settings.test"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0-alpha.2
        with:
          version: v0.4.3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
          cache: poetry
      - name: Install packages
        run: poetry install
      - name: Run DB migrations
        run: poetry run python manage.py migrate
      - name: Run collectstatic
        run: poetry run python manage.py collectstatic --noinput
      - name: Activate Environment
        run: source $(poetry env info --path)/bin/activate
      - name: Cache Pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Pre-commit
        run: poetry run pip install pre-commit
      - name: Run Pre-commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always -a --hook-stage manual
      - name: Run tests
        run: poetry run coverage run --source='.' manage.py test &&
            poetry run coverage report -m &&
            poetry run coverage html
